source_path: beaversim/utils/example_datasets/RUMNEY_MARSH/C5
output_path: beaversim/utils/output/RumneyMarsh_Boston/RGB/C5
pictures:
  general:
    target_size: None
    use_sam2: False
    baseline: mean
    shadow_correction: True        
    vegetation_index: VARI
    water_index: CWI
    threshold: -0.43     
    opening_sizes: [80]
    median_sizes: []
    closing_sizes: [40]
  C5_01:    
    image: C5_06152018.PNG
  C5_02:
    image: C5_07152018.PNG
  C5_03:
    image: C5_08212018.PNG
