source_path: beaversim/utils/example_datasets/RUMNEY_MARSH/A2
output_path: beaversim/utils/output/RumneyMarsh_Boston/RGB/A2
pictures:
  A2_01:
    image: A2_06132018.PNG
    target_size: None
    shadow_corrextion: True
    use_sam2: False
    vegetation_index: VARI
    water_index: ExG
    threshold: -0.44     
    opening_sizes: [10, 15]
    closing_sizes: [10]
  A2_02:
    image: A2_07172018.PNG
    target_size: None
    shadow_corrextion: True
    use_sam2: False
    vegetation_index: VARI
    water_index: ExG
    threshold: -0.01 
    opening_sizes: [10, 15]
    closing_sizes: [10, 10]